# Conda environment for Quantum MLOps development
name: quantum-mlops
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Python
  - python=3.11
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  
  # Machine Learning
  - pytorch>=1.12.0
  - scikit-learn>=1.0.0
  
  # Development tools
  - pip
  - make
  - git
  
  # System dependencies for quantum computing
  - openblas
  - lapack
  - gfortran_linux-64  # [linux]
  - gfortran_osx-64    # [osx]
  
  # Jupyter for development
  - jupyter
  - jupyterlab
  - ipykernel
  
  # pip-only dependencies
  - pip:
    # Quantum computing frameworks
    - pennylane>=0.33.0
    - qiskit>=0.45.0
    - qiskit-aer>=0.13.0
    - qiskit-ibm-runtime>=0.17.0
    - cirq>=1.2.0
    - amazon-braket-sdk>=1.53.0
    
    # MLOps tools
    - mlflow[extras]>=2.0.0
    - pydantic>=2.0.0
    - typer>=0.9.0
    - rich>=13.0.0
    
    # Monitoring
    - prometheus-client>=0.19.0
    - opentelemetry-api>=1.21.0
    - opentelemetry-sdk>=1.21.0
    - structlog>=23.0.0
    
    # Development tools
    - black>=23.0.0
    - ruff>=0.1.0
    - mypy>=1.8.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - pytest-xdist>=3.5.0
    - pytest-asyncio>=0.21.0
    - pre-commit>=3.6.0
    
    # Security tools
    - bandit>=1.7.5
    - safety>=2.3.5
    
    # Dependency management
    - pip-tools
    - pipdeptree