global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    cluster: 'quantum-mlops'

rule_files:
  - "quantum_mlops_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'quantum-mlops-api'
    static_configs:
      - targets: ['quantum-mlops-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'quantum-mlops-workers'
    static_configs:
      - targets: ['quantum-mlops-worker:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'quantum-hardware-metrics'
    static_configs:
      - targets: ['quantum-mlops-api:8000']
    metrics_path: '/quantum-metrics'
    scrape_interval: 60s
    scrape_timeout: 30s