apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantum-meta-learning-data-pvc
  namespace: quantum-mlops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantum-meta-learning-models-pvc
  namespace: quantum-mlops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
