global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: []
scrape_configs:
- job_name: quantum-meta-learning
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - quantum-meta-learning-service:8081
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
